package act.drools;
import zbq.entity.Sale;
import java.util.*;
import java.math.*;

//周六 、周日打9折
rule "Sat. and Sun, 90%"
	no-loop true
	lock-on-active true
	salience 1
	when 
		$s : Sale(getDayOfWeek() == 1 || getDayOfWeek() == 7)
	then
		$s.setDiscount(new BigDecimal(0.9));
		update($s);
end
//满100元打8折
rule "100￥ 80%"
	no-loop true
	lock-on-active true
	salience 2
	when 
		$s : Sale(getTotal() >= 100)
	then
		$s.setDiscount(new BigDecimal(0.8));
		update($s);
end

//200元打7折
rule "200￥ 70%"
no-loop true
	lock-on-active true
	salience 2
	when 
		$s : Sale(getTotal() >= 200)
	then
		$s.setDiscount(new BigDecimal(0.7));
		update($s);
end